from pathlib import Path

import pytest

from backend.agents import agent_registry
from backend.graph.artifacts import PROJECT_ROOT, relative_to_project, robot_output_dir
from backend.graph.nodes.automation_generator import (
    automation_generator as run_automation_generator,
)
from backend.graph.nodes.coverage_planner import coverage_planner
from backend.graph.nodes.requirement_agent import requirement_agent
from backend.graph.nodes.test_case_generator import (
    test_case_generator as run_test_case_generator,
)
from backend.graph.nodes.test_data_resolver import (
    test_data_resolver as run_test_data_resolver,
)
from backend.graph.state import ReviewFeedback
from backend.graph.state import TestContext as WorkflowContext
from backend.graph.state import TicketData
from backend.skills import skill_registry
from backend.tools import tool_registry


def _context_with_test_data() -> WorkflowContext:
    context = WorkflowContext(
        created_by="pytest",
        ticket=TicketData(
            id="AUTO-BOUNDARY-1",
            title="Money Transfer Feature",
            description="As an authenticated customer, I want to transfer money.",
            acceptance_criteria=[
                "Transfer completes within 3 seconds",
                "Balance updates immediately",
            ],
            priority="high",
            labels=["banking", "payments"],
        ),
    )
    context = requirement_agent(context)
    context = coverage_planner(context)
    context = run_test_case_generator(context)
    return run_test_data_resolver(context)


def test_automation_boundary_components_are_registered() -> None:
    assert agent_registry.has("AutomationGeneratorAgent") is True
    assert skill_registry.has("GenerateAutomationSkill") is True
    assert tool_registry.has("LocalRobotAutomationTool") is True

    agent_spec = agent_registry.get("AutomationGeneratorAgent").spec
    skill_spec = skill_registry.get("GenerateAutomationSkill").spec
    tool_spec = tool_registry.get("LocalRobotAutomationTool").spec

    assert agent_spec.skills == ("GenerateAutomationSkill",)
    assert skill_spec.tools == ("LocalRobotAutomationTool",)
    assert tool_spec.isolation == "process"


def test_automation_graph_node_preserves_existing_robot_generation() -> None:
    context = run_automation_generator(_context_with_test_data())

    assert context.workflow_status == "automation_generated"
    assert context.automation_revision == 1
    assert set(context.automation) == {"TC001", "TC002", "TC003"}
    assert context.automation["TC001"].test_case_id == "TC001"
    assert context.automation["TC001"].revision == 1
    assert context.automation["TC001"].data_reference_check_passed is True

    robot_file = PROJECT_ROOT / context.automation["TC001"].robot_file
    assert robot_file.is_file()
    assert Path(context.automation["TC001"].robot_file).as_posix() == (
        f"{relative_to_project(robot_output_dir('AUTO-BOUNDARY-1'))}/"
        "TC001_money_transfer_feature_happy_path.robot"
    )

    content = robot_file.read_text(encoding="utf-8")
    assert "*** Settings ***" in content
    assert (
        "Documentation     Generated by AegisQA for AUTO-BOUNDARY-1 / "
        "TC001 / revision 1"
    ) in content
    assert "Money Transfer Feature - Happy Path" in content
    assert "    [Tags]    generated    functional    high" in content
    assert "    Log    Step 1: Sign in as customer" in content
    assert "    Log    Expected: Primary user journey completes successfully" in content


def test_automation_graph_node_applies_open_reviewer_feedback() -> None:
    context = _context_with_test_data()
    context.automation_revision = 1
    context.review_feedback.append(
        ReviewFeedback(
            requested_by="qa_reviewer",
            comment="Please add an insufficient-funds assertion.",
        )
    )

    context = run_automation_generator(context)

    assert context.automation_revision == 2
    assert context.automation["TC001"].revision == 2
    assert context.review_feedback[0].status == "applied"

    robot_file = PROJECT_ROOT / context.automation["TC001"].robot_file
    content = robot_file.read_text(encoding="utf-8")
    assert (
        "Reviewer feedback applied: Please add an insufficient-funds assertion."
        in content
    )


def test_automation_generator_still_requires_ticket() -> None:
    context = _context_with_test_data()
    context.ticket = None

    with pytest.raises(
        ValueError,
        match="AutomationGenerator requires context.ticket",
    ):
        run_automation_generator(context)


def test_automation_generator_still_requires_test_cases() -> None:
    context = WorkflowContext(
        created_by="pytest",
        ticket=TicketData(id="AUTO-MISSING-CASES", title="Missing Cases"),
    )

    with pytest.raises(
        ValueError,
        match="AutomationGenerator requires context.test_cases",
    ):
        run_automation_generator(context)


def test_automation_generator_still_requires_test_data() -> None:
    context = _context_with_test_data()
    context.test_data = {}

    with pytest.raises(
        ValueError,
        match="AutomationGenerator requires context.test_data",
    ):
        run_automation_generator(context)
