from __future__ import annotations

from backend.graph.artifacts import relative_to_project, robot_output_dir, slug
from backend.graph.state import AutomationBlock, TestCase, TestContext


def _robot_cell(value: str) -> str:
    return value.replace("\r", " ").replace("\n", " ").replace("\t", " ").strip()


def _render_robot_file(test_case: TestCase, ticket_id: str) -> str:
    tags = ["generated", test_case.type, test_case.priority]
    lines = [
        "*** Settings ***",
        f"Documentation     Generated by AegisQA for {ticket_id} / {test_case.id}",
        "",
        "*** Test Cases ***",
        _robot_cell(test_case.title),
        f"    [Tags]    {'    '.join(tags)}",
        f"    [Documentation]    {_robot_cell(test_case.expected_outcome)}",
    ]

    for precondition in test_case.preconditions:
        lines.append(f"    Log    Preconditions: {_robot_cell(precondition)}")

    for index, step in enumerate(test_case.steps, start=1):
        lines.append(f"    Log    Step {index}: {_robot_cell(step)}")

    lines.append(f"    Log    Expected: {_robot_cell(test_case.expected_outcome)}")
    lines.append("")
    return "\n".join(lines)


def automation_generator(context: TestContext) -> TestContext:
    if context.ticket is None:
        raise ValueError("AutomationGenerator requires context.ticket")
    if not context.test_cases:
        raise ValueError("AutomationGenerator requires context.test_cases")
    if not context.test_data:
        raise ValueError("AutomationGenerator requires context.test_data")

    output_dir = robot_output_dir(context.ticket.id)
    output_dir.mkdir(parents=True, exist_ok=True)

    automation: dict[str, AutomationBlock] = {}
    for test_case in context.test_cases:
        filename = f"{test_case.id}_{slug(test_case.title)}.robot"
        robot_file = output_dir / filename
        robot_file.write_text(
            _render_robot_file(test_case, context.ticket.id),
            encoding="utf-8",
        )

        automation[test_case.id] = AutomationBlock(
            test_case_id=test_case.id,
            robot_file=relative_to_project(robot_file),
            data_reference_check_passed=test_case.id in context.test_data,
        )

    context.automation = automation
    context.mark("automation_generated")
    return context
