from __future__ import annotations

from typing import Any

from backend.graph.artifacts import relative_to_project, robot_output_dir, slug
from backend.graph.state import (
    AutomationBlock,
    ReviewFeedback,
    TestCase,
    TestDataBlock,
)
from backend.tools.base import BaseTool, tool_registry


@tool_registry.register(
    name="LocalRobotAutomationTool",
    isolation="process",
    description="Writes deterministic Robot Framework files for generated test cases.",
)
class LocalRobotAutomationTool(BaseTool):
    def invoke(self, **kwargs: Any) -> dict[str, AutomationBlock]:
        ticket_id = kwargs.get("ticket_id")
        test_cases = kwargs.get("test_cases")
        test_data = kwargs.get("test_data")
        revision = kwargs.get("revision")
        feedback = kwargs.get("feedback")

        if not isinstance(ticket_id, str) or not ticket_id.strip():
            raise TypeError("LocalRobotAutomationTool requires a ticket_id string")
        if not isinstance(test_cases, list) or not all(
            isinstance(test_case, TestCase) for test_case in test_cases
        ):
            raise TypeError("LocalRobotAutomationTool requires list[TestCase]")
        if not isinstance(test_data, dict) or not all(
            isinstance(block, TestDataBlock) for block in test_data.values()
        ):
            raise TypeError(
                "LocalRobotAutomationTool requires dict[str, TestDataBlock]"
            )
        if not isinstance(revision, int):
            raise TypeError("LocalRobotAutomationTool requires an integer revision")
        if not isinstance(feedback, list) or not all(
            isinstance(item, ReviewFeedback) for item in feedback
        ):
            raise TypeError("LocalRobotAutomationTool requires list[ReviewFeedback]")

        return generate_robot_automation(
            ticket_id=ticket_id,
            test_cases=test_cases,
            test_data=test_data,
            revision=revision,
            feedback=feedback,
        )


def generate_robot_automation(
    *,
    ticket_id: str,
    test_cases: list[TestCase],
    test_data: dict[str, TestDataBlock],
    revision: int,
    feedback: list[ReviewFeedback],
) -> dict[str, AutomationBlock]:
    output_dir = robot_output_dir(ticket_id)
    output_dir.mkdir(parents=True, exist_ok=True)

    automation: dict[str, AutomationBlock] = {}
    for test_case in test_cases:
        filename = f"{test_case.id}_{slug(test_case.title)}.robot"
        robot_file = output_dir / filename
        robot_file.write_text(
            _render_robot_file(test_case, ticket_id, revision, feedback),
            encoding="utf-8",
        )

        automation[test_case.id] = AutomationBlock(
            test_case_id=test_case.id,
            robot_file=relative_to_project(robot_file),
            revision=revision,
            data_reference_check_passed=test_case.id in test_data,
        )

    return automation


def _robot_cell(value: str) -> str:
    return value.replace("\r", " ").replace("\n", " ").replace("\t", " ").strip()


def _render_robot_file(
    test_case: TestCase,
    ticket_id: str,
    revision: int,
    feedback: list[ReviewFeedback],
) -> str:
    tags = ["generated", test_case.type, test_case.priority]
    lines = [
        "*** Settings ***",
        (
            f"Documentation     Generated by AegisQA for {ticket_id} / "
            f"{test_case.id} / revision {revision}"
        ),
        "Library           BuiltIn",
        "",
        "*** Test Cases ***",
        _robot_cell(test_case.title),
        f"    [Tags]    {'    '.join(tags)}",
        f"    [Documentation]    {_robot_cell(test_case.expected_outcome)}",
    ]

    for precondition in test_case.preconditions:
        lines.append(f"    Log    Preconditions: {_robot_cell(precondition)}")

    for index, step in enumerate(test_case.steps, start=1):
        lines.append(f"    Log    Step {index}: {_robot_cell(step)}")

    for item in feedback:
        lines.append(
            "    Log    Reviewer feedback applied: "
            f"{_robot_cell(item.comment)}"
        )

    lines.append(f"    Log    Expected: {_robot_cell(test_case.expected_outcome)}")
    lines.append("")
    return "\n".join(lines)
